import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import dts from 'vite-plugin-dts'
// import { libInjectCss } from 'vite-plugin-lib-inject-css'
import { extname, relative, resolve } from 'path'
import { fileURLToPath } from 'node:url'
import { glob } from 'glob'
import { viteStaticCopy } from 'vite-plugin-static-copy'
import eslint from 'vite-plugin-eslint'

/*
 * This is a Vite config file.
 * It is a Node.js module that exports an object.
 * https://vitejs.dev/config/
 *
 * We decide not to export css files generated by tailwindcss
 * The user must include this package into their tailwind.config.js content.
 */

// https://vite.dev/config/
export default defineConfig({
	plugins: [
		vue(),
		dts({ include: ['lib'], insertTypesEntry: true }),
		viteStaticCopy({
			targets: [
				{
					src: resolve(__dirname, './lib/assets') + '/[!.]*',
					dest: './assets',
				},
				{
					src: resolve(__dirname, './lib/config') + '/*.css',
					dest: './config',
				},
				{ src: resolve(__dirname, './scripts/') + '/[!.]*', dest: './scripts' },
			],
		}),
		eslint()
	],
	resolve: {
		alias: {
			'@': resolve(__dirname, './lib'),
			Quill: 'quill',
		},
	},
	build: {
		lib: {
			entry: resolve(__dirname, 'lib/main.ts'),
			formats: ['es'],
		},
		copyPublicDir: false,
		rollupOptions: {
			external: ['vue'],
			input: Object.fromEntries(
				glob
					.sync('lib/**/*.{ts,tsx}', {
						ignore: ['lib/**/*.d.ts'],
					})
					.map((file) => [
						// The name of the entry point
						// lib/nested/foo.ts becomes nested/foo
						relative('lib', file.slice(0, file.length - extname(file).length)),
						// The absolute path to the entry file
						// lib/nested/foo.ts becomes /project/lib/nested/foo.ts
						fileURLToPath(new URL(file, import.meta.url)),
					])
			),
			output: {
				chunkFileNames: 'chunks/[name].[hash].js',
				assetFileNames: 'assets/[name][extname]',
				entryFileNames: '[name].js',
				preserveModules: false,
			},
		},
	},
})
