const defaultTheme = require('tailwindcss/defaultTheme')
const colors = require('tailwindcss/colors')

module.exports = {
	plugins: [require('tailwindcss-animate')],
	theme: {
		screens: {
			sm: '640px',
			md: '768px',
			lg: '1024px',
			xl: '1280px',
			'2xl': '1440px',
			tablet: '768px',
			'tablet-landscape': '1024px',
			desktop: '1280px',
			wide: '1440px',
		},
		colors: {
			...colors,
			transparent: 'transparent',
			current: 'currentColor',
		},
		extend: {
			borderWidth: {
				'1': '1px',
			},
			keyframes: {
				'accordion-down': {
					from: { height: 0 },
					to: { height: 'var(--reka-accordion-content-height)' },
				},
				'accordion-up': {
					from: { height: 'var(--reka-accordion-content-height)' },
					to: { height: 0 },
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
			},
			colors: {
				primary: {
					50: 'rgba(var(--color-primary-50) / <alpha-value>)',
					100: 'rgba(var(--color-primary-100) / <alpha-value>)',
					200: 'rgba(var(--color-primary-200) / <alpha-value>)',
					300: 'rgba(var(--color-primary-300) / <alpha-value>)',
					400: 'rgba(var(--color-primary-400) / <alpha-value>)',
					500: 'rgba(var(--color-primary-500) / <alpha-value>)',
					600: 'rgba(var(--color-primary-600) / <alpha-value>)',
					700: 'rgba(var(--color-primary-700) / <alpha-value>)',
					800: 'rgba(var(--color-primary-800) / <alpha-value>)',
					900: 'rgba(var(--color-primary-900) / <alpha-value>)',
					950: 'rgba(var(--color-primary-950) / <alpha-value>)',
				},
				secondary: {
					50: 'rgba(var(--color-secondary-50) / <alpha-value>)',
					100: 'rgba(var(--color-secondary-100) / <alpha-value>)',
					200: 'rgba(var(--color-secondary-200) / <alpha-value>)',
					300: 'rgba(var(--color-secondary-300) / <alpha-value>)',
					400: 'rgba(var(--color-secondary-400) / <alpha-value>)',
					500: 'rgba(var(--color-secondary-500) / <alpha-value>)',
					600: 'rgba(var(--color-secondary-600) / <alpha-value>)',
					700: 'rgba(var(--color-secondary-700) / <alpha-value>)',
					800: 'rgba(var(--color-secondary-800) / <alpha-value>)',
					900: 'rgba(var(--color-secondary-900) / <alpha-value>)',
					950: 'rgba(var(--color-secondary-950) / <alpha-value>)',
				},
				warning: {
					50: 'rgba(var(--color-warning-50) / <alpha-value>)',
					100: 'rgba(var(--color-warning-100) / <alpha-value>)',
					200: 'rgba(var(--color-warning-200) / <alpha-value>)',
					300: 'rgba(var(--color-warning-300) / <alpha-value>)',
					400: 'rgba(var(--color-warning-400) / <alpha-value>)',
					500: 'rgba(var(--color-warning-500) / <alpha-value>)',
					600: 'rgba(var(--color-warning-600) / <alpha-value>)',
					700: 'rgba(var(--color-warning-700) / <alpha-value>)',
					800: 'rgba(var(--color-warning-800) / <alpha-value>)',
					900: 'rgba(var(--color-warning-900) / <alpha-value>)',
					950: 'rgba(var(--color-warning-950) / <alpha-value>)',
				},
				success: {
					50: 'rgba(var(--color-success-50) / <alpha-value>)',
					100: 'rgba(var(--color-success-100) / <alpha-value>)',
					200: 'rgba(var(--color-success-200) / <alpha-value>)',
					300: 'rgba(var(--color-success-300) / <alpha-value>)',
					400: 'rgba(var(--color-success-400) / <alpha-value>)',
					500: 'rgba(var(--color-success-500) / <alpha-value>)',
					600: 'rgba(var(--color-success-600) / <alpha-value>)',
					700: 'rgba(var(--color-success-700) / <alpha-value>)',
					800: 'rgba(var(--color-success-800) / <alpha-value>)',
					900: 'rgba(var(--color-success-900) / <alpha-value>)',
					950: 'rgba(var(--color-success-950) / <alpha-value>)',
				},
				danger: {
					50: 'rgba(var(--color-danger-50) / <alpha-value>)',
					100: 'rgba(var(--color-danger-100) / <alpha-value>)',
					200: 'rgba(var(--color-danger-200) / <alpha-value>)',
					300: 'rgba(var(--color-danger-300) / <alpha-value>)',
					400: 'rgba(var(--color-danger-400) / <alpha-value>)',
					500: 'rgba(var(--color-danger-500) / <alpha-value>)',
					600: 'rgba(var(--color-danger-600) / <alpha-value>)',
					700: 'rgba(var(--color-danger-700) / <alpha-value>)',
					800: 'rgba(var(--color-danger-800) / <alpha-value>)',
					900: 'rgba(var(--color-danger-900) / <alpha-value>)',
					950: 'rgba(var(--color-danger-950) / <alpha-value>)',
				},
				neutral: {
					50: 'rgba(var(--color-neutral-50) / <alpha-value>)',
					100: 'rgba(var(--color-neutral-100) / <alpha-value>)',
					200: 'rgba(var(--color-neutral-200) / <alpha-value>)',
					300: 'rgba(var(--color-neutral-300) / <alpha-value>)',
					400: 'rgba(var(--color-neutral-400) / <alpha-value>)',
					500: 'rgba(var(--color-neutral-500) / <alpha-value>)',
					600: 'rgba(var(--color-neutral-600) / <alpha-value>)',
					700: 'rgba(var(--color-neutral-700) / <alpha-value>)',
					800: 'rgba(var(--color-neutral-800) / <alpha-value>)',
					900: 'rgba(var(--color-neutral-900) / <alpha-value>)',
					950: 'rgba(var(--color-neutral-950) / <alpha-value>)',
				},
				info: {
					50: 'rgba(var(--color-info-50) / <alpha-value>)',
					100: 'rgba(var(--color-info-100) / <alpha-value>)',
					200: 'rgba(var(--color-info-200) / <alpha-value>)',
					300: 'rgba(var(--color-info-300) / <alpha-value>)',
					400: 'rgba(var(--color-info-400) / <alpha-value>)',
					500: 'rgba(var(--color-info-500) / <alpha-value>)',
					600: 'rgba(var(--color-info-600) / <alpha-value>)',
					700: 'rgba(var(--color-info-700) / <alpha-value>)',
					800: 'rgba(var(--color-info-800) / <alpha-value>)',
					900: 'rgba(var(--color-info-900) / <alpha-value>)',
					950: 'rgba(var(--color-info-950) / <alpha-value>)',
				},
				orange: {
					50: 'rgba(var(--color-orange-50) / <alpha-value>)',
					100: 'rgba(var(--color-orange-100) / <alpha-value>)',
					200: 'rgba(var(--color-orange-200) / <alpha-value>)',
					300: 'rgba(var(--color-orange-300) / <alpha-value>)',
					400: 'rgba(var(--color-orange-400) / <alpha-value>)',
					500: 'rgba(var(--color-orange-500) / <alpha-value>)',
					600: 'rgba(var(--color-orange-600) / <alpha-value>)',
					700: 'rgba(var(--color-orange-700) / <alpha-value>)',
					800: 'rgba(var(--color-orange-800) / <alpha-value>)',
					900: 'rgba(var(--color-orange-900) / <alpha-value>)',
					950: 'rgba(var(--color-orange-950) / <alpha-value>)',
				},
				white: '#ffffff',
				black: '#000000',
			},
			fontFamily: {
				sans: ['Inter', ...defaultTheme.fontFamily.sans],
			},
			fontSize: {
				xs: '0.75rem',
				sm: '0.875rem',
				base: '1rem',
				lg: '1.125rem',
				xl: '1.25rem',
				'2xl': '1.5rem',
				'3xl': '1.875rem',
				'display-xl': [
					'96px',
					{ lineHeight: '108px', letterSpacing: '-2px' },
				],
				'display-lg': [
					'80px',
					{ lineHeight: '92px', letterSpacing: '-3px' },
				],
				'display-md': [
					'64px',
					{ lineHeight: '76px', letterSpacing: '-2px' },
				],
				'display-sm': [
					'52px',
					{ lineHeight: '64px', letterSpacing: '-2px' },
				],
				'heading-xl': [
					'40px',
					{ lineHeight: '52px', letterSpacing: '-1px' },
				],
				'heading-lg': [
					'36px',
					{ lineHeight: '48px', letterSpacing: '-1px' },
				],
				'heading-md': [
					'32px',
					{ lineHeight: '44px', letterSpacing: '-1px' },
				],
				'heading-sm': [
					'28px',
					{ lineHeight: '40px', letterSpacing: '0' },
				],
				'title-lg': [
					'24px',
					{ lineHeight: '36px', letterSpacing: '0' },
				],
				'title-md': [
					'22px',
					{ lineHeight: '32px', letterSpacing: '0' },
				],
				'title-sm': [
					'20px',
					{ lineHeight: '30px', letterSpacing: '0' },
				],
				'body-lg': [
					'18px',
					{ lineHeight: '28px', letterSpacing: '0' },
				],
				'body-md': [
					'16px',
					{ lineHeight: '24px', letterSpacing: '0' },
				],
				'body-sm': [
					'14px',
					{ lineHeight: '20px', letterSpacing: '0' },
				],
				'label-lg': [
					'16px',
					{ lineHeight: '24px', letterSpacing: '0' },
				],
				'label-md': [
					'14px',
					{ lineHeight: '20px', letterSpacing: '0' },
				],
				'label-sm': [
					'12px',
					{ lineHeight: '16px', letterSpacing: '0' },
				],
				'caption-md': [
					'12px',
					{ lineHeight: '16px', letterSpacing: '0' },
				],
				'caption-sm': [
					'11px',
					{ lineHeight: '16px', letterSpacing: '0' },
				],
			},
			fontWeight: {
				normal: '400',
				semibold: '600',
				bold: '700',
			},
			boxShadow: {
				'1': '0 1px 2px 0 rgba(var(--color-neutral-950) / 0.1)',
				'2': '0 4px 8px 0 rgba(var(--color-neutral-950) / 0.1)',
				'3': 'inset 1px 2px 2px 0 rgba(var(--color-neutral-950) / 0.12)',
			},
		},
	},
}
