import fs from 'fs'
import path from 'path'
import { execSync } from 'child_process'
import svgpath from 'svgpath'

//#region selection.json to svg font
// Paths and configuration
const selectionPath = 'assets/icomoon/selection.json'

const fontName = 'suteki-icon'

// Read selection.json
const selection = JSON.parse(fs.readFileSync(selectionPath, 'utf-8'))
const icons = selection.glyphs

const VIEWBOX = 24
const FONT_SIZE = 1024
const SCALE = FONT_SIZE / VIEWBOX

const pathObjectToD = (paths) => {
	return paths
		.map(subpath => {
			const [sx, sy] = subpath.start
			let d = `M${sx * SCALE} ${sy * SCALE}`
			for (const cmd of subpath.cmds || []) {
				if (cmd.tag === 'LineTo') {
					const [x, y] = cmd.args[0].point
					d += `L${x * SCALE} ${y * SCALE}`
				} else if (cmd.tag === 'BezierCurveTo') {
					const { c1, c2, end } = cmd.args[0].args[0]
					d += `C${c1[0] * SCALE} ${c1[1] * SCALE} ${c2[0] * SCALE} ${c2[1] * SCALE} ${end[0] * SCALE} ${end[1] * SCALE}`
				}
			}
			return d
		})
		.join('')
}

const extractD = (glyph) => {
	const children = glyph.node?.args?.[0]?.children || []
	return children
		.filter(c => c.args?.[0]?.tagName === 'path')
		.map(c => {
			const dAttr = c.args[0].attributes.d
			if (!dAttr) return ''
			if (dAttr.tag === 'StringValue') return dAttr.args[0]
			if (dAttr.tag === 'Value') {
				const paths = dAttr.args?.[0]?.args?.[0]
				return Array.isArray(paths) ? pathObjectToD(paths) : ''
			}
			return ''
		})
		.join('')
}

// Header for each SVG file (shared font structure)
let svgContent =
	`<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg">
<metadata>Generated by IcoMoon</metadata>
<defs>
<font id="suteki-icon" horiz-adv-x="1024">
<font-face units-per-em="1024" ascent="960" descent="-64" />
<missing-glyph horiz-adv-x="1024" />
<glyph unicode="&#x20;" horiz-adv-x="512" d="" />`.trim() + '\n'

console.log('\nGenerating SVG font...')

// Generate individual SVG files for each icon
icons.forEach((icon) => {
  const name = icon.extras.name
  const d = extractD(icon)
  const unicode = icon.extras.codePoint.toString(16)

  const glyphContent = `<glyph unicode="&#x${unicode};" glyph-name="${name}" d="${d}" />`.trim()

  svgContent += glyphContent + '\n'
})

svgContent += `</font></defs></svg>`

svgContent = svgContent.replace(
	/(<glyph[^>]*d=")([^"]+)(")/g,
	(_, start, d, end) => {
		const flippedPath = svgpath(d).scale(1, -1).translate(0, 975).toString()
		return `${start}${flippedPath}${end}`
	}
)

const outputDir = 'assets/icomoon/svg'

deleteFileOnFolder(outputDir)

const outputPath = path.join(outputDir, `${fontName}.svg`)
fs.writeFileSync(outputPath, svgContent)

console.log(`✅ SVG font generated at ${outputPath}`)
//#endregion

//#region Convert SVG font to Ttf
const fontOutputFolder = 'assets/icomoon/ttf'

deleteFileOnFolder(fontOutputFolder)

const ttfPath = path.join(fontOutputFolder, `${fontName}.ttf`)
const svgSource = path.join(outputDir, `${fontName}.svg`)
console.log('\nGenerating TTF...')

try {
	const command = `svg2ttf ${svgSource} ${ttfPath}`
	execSync(command, { stdio: 'inherit' })
	console.log(`✅ Ttf generated at ${ttfPath}`)
} catch (error) {
	console.error('❌ Failed to generate Ttf:', error.message)
}
//#endregion

//#region Convert Ttf to Woff
const woffOutputFolder = 'assets/icomoon/woff'

deleteFileOnFolder(woffOutputFolder)

const woffPath = path.join(woffOutputFolder, `${fontName}.woff`)
console.log('\nGenerating WOFF...')

try {
	const command = `ttf2woff ${ttfPath} ${woffPath}`
	execSync(command, { stdio: 'inherit' })
	console.log(`✅ Woff generated at ${woffPath}`)
} catch (error) {
	console.error('❌ Failed to generate WOFF:', error.message)
}
//#endregion

function deleteFileOnFolder(dir) {
	if (fs.existsSync(dir)) {
		for (const file of fs.readdirSync(dir)) {
			const filePath = path.join(dir, file)
			if (fs.lstatSync(filePath).isFile()) {
				fs.unlinkSync(filePath)
			}
		}
	} else {
		fs.mkdirSync(dir, { recursive: true })
	}
}
