import fs from 'fs'
import path from 'path'
import { execSync } from 'child_process'
import svgpath from 'svgpath'

//#region selection.json to svg font
// Paths and configuration
const selectionPath = 'assets/icomoon/selection.json'

const fontName = 'suteki-icon'

// Read selection.json
const selection = JSON.parse(fs.readFileSync(selectionPath, 'utf-8'))
const icons = selection.icons

// Header for each SVG file (shared font structure)
let svgContent =
	`<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg">
<metadata>Generated by IcoMoon</metadata>
<defs>
<font id="suteki-icon" horiz-adv-x="1024">
<font-face units-per-em="1024" ascent="960" descent="-64" />
<missing-glyph horiz-adv-x="1024" />
<glyph unicode="&#x20;" horiz-adv-x="512" d="" />`.trim() + '\n'

console.log('\nGenerating SVG font...')

// Generate individual SVG files for each icon
icons.forEach((icon) => {
	const name = icon.properties.name
	const paths = icon.icon.paths
	const unicode = icon.properties.code.toString(16)

	const glyphContent =
		`<glyph unicode="&#x${unicode};" glyph-name="${name}" d="${paths}" />`.trim()

	svgContent += glyphContent + '\n'
})

svgContent += `</font></defs></svg>`

svgContent = svgContent.replace(
	/(<glyph[^>]*d=")([^"]+)(")/g,
	(_, start, d, end) => {
		const flippedPath = svgpath(d).scale(1, -1).translate(0, 1024).toString()
		return `${start}${flippedPath}${end}`
	}
)

const outputDir = 'assets/icomoon/svg'

deleteFileOnFolder(outputDir)

const outputPath = path.join(outputDir, `${fontName}.svg`)
fs.writeFileSync(outputPath, svgContent)

console.log(`✅ SVG font generated at ${outputPath}`)
//#endregion

//#region Convert SVG font to Ttf
const fontOutputFolder = 'assets/icomoon/ttf'

deleteFileOnFolder(fontOutputFolder)

const ttfPath = path.join(fontOutputFolder, `${fontName}.ttf`)
const svgSource = path.join(outputDir, `${fontName}.svg`)
console.log('\nGenerating TTF...')

try {
	const command = `svg2ttf ${svgSource} ${ttfPath}`
	execSync(command, { stdio: 'inherit' })
	console.log(`✅ Ttf generated at ${ttfPath}`)
} catch (error) {
	console.error('❌ Failed to generate Ttf:', error.message)
}
//#endregion

//#region Convert Ttf to Woff
const woffOutputFolder = 'assets/icomoon/woff'

deleteFileOnFolder(woffOutputFolder)

const woffPath = path.join(woffOutputFolder, `${fontName}.woff`)
console.log('\nGenerating WOFF...')

try {
	const command = `ttf2woff ${ttfPath} ${woffPath}`
	execSync(command, { stdio: 'inherit' })
	console.log(`✅ Woff generated at ${woffPath}`)
} catch (error) {
	console.error('❌ Failed to generate WOFF:', error.message)
}
//#endregion

function deleteFileOnFolder(dir) {
	if (fs.existsSync(dir)) {
		for (const file of fs.readdirSync(dir)) {
			const filePath = path.join(dir, file)
			if (fs.lstatSync(filePath).isFile()) {
				fs.unlinkSync(filePath)
			}
		}
	} else {
		fs.mkdirSync(dir, { recursive: true })
	}
}
